services:
  - type: web
    name: gadsden-app
    runtime: python
    buildCommand: cd gadsden-app && pip install -r requirements.txt
    startCommand: cd gadsden-app && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
